### ISSUE TITLE
Name should be proj4 or proj.4?

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/proj.4-feedstock#12]
Long time ago, before conda-forge, we renamed `proj4` to `proj.4` to match `defaults`. See https://github.com/SciTools/conda-recipes-scitools/pull/116 and https://github.com/ioos/conda-recipes/pull/500

Now it seems that `defaults` renamed it back to `proj4` and we have the same problem because this feedstock was based on the `scitools` package.

Not sure if we should rename it again but some consistency would be nice. Pinging @msarahan and @ccordoba12 in case you know the reasons for the re-rename.

BTW: `proj.4` **is** the original name so maybe we should stick with that.

**Comment by jjhelmus** [comment]
Was having issue with the name mismatch today.  Having both `proj.4` and `proj4` installed in a environment can cause segmentation faults.  

My vote is for `proj4` although I would rather see this resolved rather than have a particular name.

**Comment by ocefpaf** [comment]
What do you say @msarahan? Will `defaults` settle on `proj4`? If so I will gladly rename it here and fix the dependencies.

**Comment by ocefpaf** [comment]
OK. No one from continuum said anything... I will rename and go about all the feedstocks renaming the dependencies, but if this changes again :imp: :imp: :imp:

**Comment by jakirkham** [comment]
Should we rename the feedstock to match the current package name?

**Comment by kbevers** [comment]
As the maintainer of PROJ I would encourage that since the proj4 moniker is rather confusing now that we've moved past version 4. The project is trying to move away from the having the 4 in the name wherever possible, but as you can imagine moving away from a name that has been in use for over 25 years is a slow process. I expect this will take 5 to 10 years so if conda-forge continues to use the proj4 name it will not be a big deal in the grand scheme of things.
