### ISSUE TITLE
Relax PROJ 9 pin

### ISSUE THREAD

**Issue by speleo3** [conda-forge/proj.4-feedstock#144]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

`run_exports` is pinned to `x.x.x`. This has been discussed 5 years ago in https://github.com/conda-forge/proj.4-feedstock/issues/64

I like to reopen this issue because at least since version 8.0.0, backward compatibility and semantic versioning compliance looks very solid: https://abi-laboratory.pro/?view=timeline&l=proj

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by xylar** [comment]
@speleo3, I agree, the ABI looks pretty stable.  I'd like to hear from others, though.  @snowman2, do you have a sense of whether this would be safe?  Other opinions among the @conda-forge/proj-4 maintainers?

**Comment by hobu** [comment]
Concur to relax to `x.x` for PROJ >= 8.0 going forward.

**Comment by snowman2** [comment]
> Concur to relax to `x.x` for PROJ >= 8.0 going forward.

I also agree that this would be safe.

**Comment by xylar** [comment]
Great, thanks!  The next steps would be to figure out if we have to revisit the ppc64le issue or not (see https://github.com/conda-forge/gdal-feedstock/issues/918#issuecomment-2107865706), since maybe this change would piggyback on that if so, and we would need to update conda-forge-pinning: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/main/recipe/migrations/proj940.yaml#L8
